version: '3.3'

services:

  loader:
    image: loader
    build:
      context: ./elastic/
    volumes:
      - ./database:/app/
    depends_on:
      - elasticsearch
    enviroment:
    - PYTHONUNBUFFERED=0

  elasticsearch:
    image: elasticsearch:6.7.1
    ports:
      - "9200:9200"

  kibana:
    image: blacktop/kibana:6.7
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
